import { expect, test } from '@playwright/test';

const skill = { id: '550e8400-e29b-41d4-a716-446655440000', codigo: 'EF01CO01', eixo: 'PENSAMENTO_COMPUTACIONAL', descricao: 'Criar algoritmos.', explicacao: '', exemplos: [], ativa: true, etapa: { id: 'stage', codigo: 'EF01', nome: '1º ano', anoInicial: 1, anoFinal: 1, ativo: true, nivel: { id: 'level', codigo: 'ENSINO_FUNDAMENTAL', nome: 'Ensino Fundamental', ativo: true } } };
const plan = { id: 'plan', ownerId: 'owner', status: 'RASCUNHO', markdown: '# Aula', aiAssisted: true, references: [{ title: 'BNCC' }], aiRun: { skills: [{ habilidade: skill }] } };

test('professor seleciona BNCC, espera a geração e recebe um rascunho assistido por IA', async ({ page }) => {
  await page.route('**/api/v1/**', async route => { const path = new URL(route.request().url()).pathname; if (path.endsWith('/auth/refresh')) return route.fulfill({ json: { accessToken: 'token' } }); if (path.endsWith('/bncc/skills')) return route.fulfill({ json: { data: [skill], meta: { page: 1, pageSize: 100, total: 1, totalPages: 1 } } }); if (path.endsWith('/plans') && route.request().method() === 'GET') return route.fulfill({ json: [] }); if (path.endsWith('/plans/generations')) { await new Promise((resolve) => setTimeout(resolve, 25)); return route.fulfill({ json: plan, status: 201 }); } await route.fallback(); });
  await page.goto('/planos'); await page.getByRole('combobox', { name: 'Buscar por código ou texto' }).fill('EF01'); await page.getByRole('button', { name: /EF01CO01/ }).click(); await expect(page.getByRole('button', { name: 'Remover EF01CO01' })).toBeVisible(); await page.getByLabel('Instrução pedagógica').fill('Construir algoritmo'); await page.getByRole('button', { name: 'Gerar plano de aula' }).click(); await expect(page.getByText('Gerando rascunho…')).toBeVisible(); await expect(page.getByText('Assistido por IA')).toBeVisible(); await expect(page.getByLabel('Markdown')).toHaveValue('# Aula');
});

test('falha preserva o formulário e só tenta novamente por novo envio', async ({ page }) => {
  let attempts = 0; await page.route('**/api/v1/**', async route => { const path = new URL(route.request().url()).pathname; if (path.endsWith('/auth/refresh')) return route.fulfill({ json: { accessToken: 'token' } }); if (path.endsWith('/bncc/skills')) return route.fulfill({ json: { data: [skill], meta: { page: 1, pageSize: 100, total: 1, totalPages: 1 } } }); if (path.endsWith('/plans') && route.request().method() === 'GET') return route.fulfill({ json: [] }); if (path.endsWith('/plans/generations')) { attempts += 1; return route.fulfill({ status: 502, body: 'unavailable' }); } await route.fallback(); });
  await page.goto('/planos'); await page.getByRole('combobox', { name: 'Buscar por código ou texto' }).fill('EF01'); await page.getByRole('button', { name: /EF01CO01/ }).click(); await page.getByLabel('Instrução pedagógica').fill('Manter contexto'); await page.getByRole('button', { name: 'Gerar plano de aula' }).click(); await expect(page.getByText('A geração não foi concluída. Confira os dados e tente novamente.')).toBeVisible(); await expect(page.getByLabel('Instrução pedagógica')).toHaveValue('Manter contexto'); await expect(page.getByRole('button', { name: 'Remover EF01CO01' })).toBeVisible(); expect(attempts).toBe(1);
});
