'use client';

import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api-client';
import { Level, Page, Skill, Stage } from '../../lib/bncc-api';
import { useSession } from '../auth/auth-session-provider';
import { Button, Dialog, EmptyState, Notice, Panel } from '../ui/ui';

type Json = Record<string, unknown>;
type Editing = { kind: 'level'; value: Level } | { kind: 'stage'; value: Stage } | { kind: 'skill'; value: Skill };
const axisOptions = ['', 'PENSAMENTO_COMPUTACIONAL', 'MUNDO_DIGITAL', 'CULTURA_DIGITAL'];

export function CatalogAdmin() {
  const { accessToken, ready, setToken } = useSession();
  const [levels, setLevels] = useState<Level[]>([]); const [stages, setStages] = useState<Stage[]>([]); const [skills, setSkills] = useState<Skill[]>([]);
  const [levelId, setLevelId] = useState(''); const [stageId, setStageId] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [loading, setLoading] = useState(false); const [editing, setEditing] = useState<Editing>();
  const request = useCallback(async <T,>(path: string, init?: RequestInit) => { if (!accessToken) throw new Error('Sessão ausente.'); return apiRequest<T>(path, accessToken, setToken, init); }, [accessToken, setToken]);
  const load = useCallback(async () => { if (!accessToken) return; try { setLoading(true); setError(''); const nextLevels = await request<Level[]>('/admin/bncc/levels'); setLevels(nextLevels); const currentLevelId = levelId || nextLevels[0]?.id || ''; setLevelId(currentLevelId); if (!currentLevelId) { setStages([]); setSkills([]); return; } const nextStages = await request<Stage[]>(`/admin/bncc/levels/${currentLevelId}/stages`); setStages(nextStages); const currentStageId = stageId || nextStages[0]?.id || ''; setStageId(currentStageId); const page = await request<Page>('/admin/bncc/skills?page=1&pageSize=100'); setSkills(page.data); } catch { setError('Acesso ADMIN necessário ou catálogo indisponível.'); } finally { setLoading(false); } }, [accessToken, levelId, request, stageId]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (path: string, method: 'POST' | 'PATCH', body: Json) => { try { setError(''); await request(path, { method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); await load(); setNotice('Alteração salva e auditada.'); return true; } catch { setError('Não foi possível salvar. Verifique os dados, permissões e unicidade.'); return false; } };
  const submitLevel = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); void mutate('/admin/bncc/levels', 'POST', { code: data.get('code'), name: data.get('name') }).then(saved => { if (saved) form.reset(); }); };
  const submitStage = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!levelId) return; const form = event.currentTarget; const data = new FormData(form); const value = (name: string) => data.get(name) === '' ? null : Number(data.get(name)); void mutate(`/admin/bncc/levels/${levelId}/stages`, 'POST', { code: data.get('code'), name: data.get('name'), yearStart: value('yearStart'), yearEnd: value('yearEnd') }).then(saved => { if (saved) form.reset(); }); };
  const submitSkill = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!stageId) return; const form = event.currentTarget; const data = new FormData(form); const examples = String(data.get('examples')).split('\n').map(value => value.trim()).filter(Boolean); void mutate(`/admin/bncc/stages/${stageId}/skills`, 'POST', { code: data.get('code'), axis: data.get('axis') || null, description: data.get('description'), explanation: data.get('explanation'), examples }).then(saved => { if (saved) form.reset(); }); };
  const saveEdit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const data = new FormData(event.currentTarget); let path = ''; let body: Json = {}; if (editing.kind === 'level') { path = `/admin/bncc/levels/${editing.value.id}`; body = { name: data.get('name') }; } else if (editing.kind === 'stage') { const year = (name: string) => data.get(name) === '' ? null : Number(data.get(name)); path = `/admin/bncc/stages/${editing.value.id}`; body = { name: data.get('name'), yearStart: year('yearStart'), yearEnd: year('yearEnd') }; } else { path = `/admin/bncc/skills/${editing.value.id}`; body = { description: data.get('description'), explanation: data.get('explanation'), axis: data.get('axis') || null, examples: String(data.get('examples')).split('\n').map(value => value.trim()).filter(Boolean) }; } void mutate(path, 'PATCH', body).then(saved => { if (saved) setEditing(undefined); }); };
  if (!ready) return <div className="page-wrap"><Notice status>Verificando sessão…</Notice></div>;
  if (!accessToken) return <div className="page-wrap"><EmptyState title="Faça login como ADMIN para administrar o catálogo.">O backend confirma a permissão antes de qualquer alteração.</EmptyState></div>;
  return <section className="page-wrap"><header className="page-header"><div><span className="eyebrow">Curadoria do catálogo</span><h1>Administração do catálogo BNCC</h1><p>Os controles apenas solicitam mudanças; o backend valida o papel ADMIN, a integridade e registra auditoria.</p></div><a className="brand" href="/"><span className="brand-mark" aria-hidden="true">✓</span><span>Planejador BNCC</span></a></header>{error && <Notice tone="error">{error}</Notice>}{notice && <Notice tone="success" status>{notice}</Notice>}{loading && <Notice status>Carregando catálogo administrativo…</Notice>}<div className="button-row"><Button type="button" variant="secondary" onClick={() => void load()} disabled={loading}>Atualizar catálogo</Button></div>
    <div className="admin-grid">
      <Panel><h2>Níveis</h2><form className="grid" onSubmit={submitLevel}><label className="field">Código<select name="code" required defaultValue=""><option value="" disabled>Selecione o nível</option><option value="EDUCACAO_INFANTIL">Educação Infantil</option><option value="ENSINO_FUNDAMENTAL">Ensino Fundamental</option><option value="ENSINO_MEDIO">Ensino Médio</option></select></label><label className="field">Nome<input name="name" required maxLength={100} /></label><Button>Criar nível</Button></form><div className="entity-list">{levels.map(level => <div className="list-row" key={level.id}><div className="list-row-main"><strong>{level.nome}</strong><span>{level.ativo ? 'Ativo' : 'Inativo'}</span></div><div className="button-row"><Button type="button" variant="ghost" className="small" onClick={() => { setLevelId(level.id); setStageId(''); }}>Selecionar</Button><Button type="button" variant="ghost" className="small" onClick={() => setEditing({ kind: 'level', value: level })}>Editar</Button><Button type="button" variant={level.ativo ? 'danger' : 'secondary'} className="small" onClick={() => void mutate(`/admin/bncc/levels/${level.id}`, 'PATCH', { active: !level.ativo })}>{level.ativo ? 'Desativar' : 'Ativar'}</Button></div></div>)}</div></Panel>
      <Panel><h2>Etapas</h2><label className="field">Nível<select value={levelId} onChange={event => { setLevelId(event.target.value); setStageId(''); }}><option value="">Selecione</option>{levels.map(level => <option key={level.id} value={level.id}>{level.nome}</option>)}</select></label><form className="grid" onSubmit={submitStage}><label className="field">Código<input name="code" required maxLength={40} /></label><label className="field">Nome<input name="name" required maxLength={100} /></label><div className="grid two"><label className="field">Ano inicial<input name="yearStart" type="number" min="1" /></label><label className="field">Ano final<input name="yearEnd" type="number" min="1" /></label></div><Button disabled={!levelId}>Criar etapa</Button></form><div className="entity-list">{stages.map(stage => <div className="list-row" key={stage.id}><div className="list-row-main"><strong>{stage.nome}</strong><span>{stage.ativo ? 'Ativa' : 'Inativa'}</span></div><div className="button-row"><Button type="button" variant="ghost" className="small" onClick={() => setStageId(stage.id)}>Selecionar</Button><Button type="button" variant="ghost" className="small" onClick={() => setEditing({ kind: 'stage', value: stage })}>Editar</Button><Button type="button" variant={stage.ativo ? 'danger' : 'secondary'} className="small" onClick={() => void mutate(`/admin/bncc/stages/${stage.id}`, 'PATCH', { active: !stage.ativo })}>{stage.ativo ? 'Desativar' : 'Ativar'}</Button></div></div>)}</div></Panel>
      <Panel><h2>Habilidades</h2><label className="field">Etapa<select value={stageId} onChange={event => setStageId(event.target.value)}><option value="">Selecione</option>{stages.map(stage => <option key={stage.id} value={stage.id}>{stage.nome}</option>)}</select></label><form className="grid" onSubmit={submitSkill}><label className="field">Código BNCC<input name="code" required maxLength={40} /></label><label className="field">Eixo<select name="axis">{axisOptions.map(option => <option key={option} value={option}>{option || 'Eixo pendente'}</option>)}</select></label><label className="field">Descrição<textarea name="description" required /></label><label className="field">Explicação<textarea name="explanation" required /></label><label className="field">Exemplos (um por linha)<textarea name="examples" required /></label><Button disabled={!stageId}>Criar habilidade</Button></form><div className="entity-list">{skills.map(skill => <div className="list-row" key={skill.id}><div className="list-row-main"><strong>{skill.codigo}</strong><span>{skill.ativa ? 'Ativa' : 'Inativa'}</span></div><div className="button-row"><Button type="button" variant="ghost" className="small" onClick={() => setEditing({ kind: 'skill', value: skill })}>Editar</Button><Button type="button" variant={skill.ativa ? 'danger' : 'secondary'} className="small" onClick={() => void mutate(`/admin/bncc/skills/${skill.id}`, 'PATCH', { active: !skill.ativa })}>{skill.ativa ? 'Desativar' : 'Ativar'}</Button></div></div>)}</div></Panel>
    </div>
    {editing && <Dialog title={editing.kind === 'level' ? 'Editar nível' : editing.kind === 'stage' ? 'Editar etapa' : 'Editar habilidade'} onClose={() => setEditing(undefined)}><form className="grid" onSubmit={saveEdit}>{editing.kind === 'level' && <label className="field">Nome<input name="name" required maxLength={100} defaultValue={editing.value.nome} /></label>}{editing.kind === 'stage' && <><label className="field">Nome<input name="name" required maxLength={100} defaultValue={editing.value.nome} /></label><div className="grid two"><label className="field">Ano inicial<input name="yearStart" type="number" min="1" defaultValue={editing.value.anoInicial ?? ''} /></label><label className="field">Ano final<input name="yearEnd" type="number" min="1" defaultValue={editing.value.anoFinal ?? ''} /></label></div></>}{editing.kind === 'skill' && <><label className="field">Descrição<textarea name="description" required defaultValue={editing.value.descricao} /></label><label className="field">Explicação<textarea name="explanation" required defaultValue={editing.value.explicacao} /></label><label className="field">Eixo<select name="axis" defaultValue={editing.value.eixo ?? ''}>{axisOptions.map(option => <option key={option} value={option}>{option || 'Eixo pendente'}</option>)}</select></label><label className="field">Exemplos (um por linha)<textarea name="examples" required defaultValue={editing.value.exemplos.map(example => example.texto).join('\n')} /></label></>}<div className="button-row"><Button type="submit">Salvar alterações</Button><Button type="button" variant="ghost" onClick={() => setEditing(undefined)}>Cancelar</Button></div></form></Dialog>}
  </section>;
}
