'use client';
import React, { FormEvent, useCallback, useEffect, useState } from 'react';
import { apiRequest } from '../../lib/api-client';
import { Level, Page, Skill, Stage } from '../../lib/bncc-api';
import { useSession } from '../auth/auth-session-provider';

type Json = Record<string, unknown>;
const axisOptions = ['', 'PENSAMENTO_COMPUTACIONAL', 'MUNDO_DIGITAL', 'CULTURA_DIGITAL'];

export function CatalogAdmin() {
  const { accessToken, ready, setToken } = useSession();
  const [levels, setLevels] = useState<Level[]>([]); const [stages, setStages] = useState<Stage[]>([]); const [skills, setSkills] = useState<Skill[]>([]);
  const [levelId, setLevelId] = useState(''); const [stageId, setStageId] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const request = useCallback(async <T,>(path: string, init?: RequestInit) => { if (!accessToken) throw new Error('Sessão ausente.'); return apiRequest<T>(path, accessToken, setToken, init); }, [accessToken, setToken]);
  const load = useCallback(async () => { if (!accessToken) return; try { setError(''); const nextLevels = await request<Level[]>('/admin/bncc/levels'); setLevels(nextLevels); const currentLevelId = levelId || nextLevels[0]?.id || ''; setLevelId(currentLevelId); if (!currentLevelId) { setStages([]); setSkills([]); return; } const nextStages = await request<Stage[]>(`/admin/bncc/levels/${currentLevelId}/stages`); setStages(nextStages); const currentStageId = stageId || nextStages[0]?.id || ''; setStageId(currentStageId); const page = await request<Page>('/admin/bncc/skills?page=1&pageSize=100'); setSkills(page.data); } catch { setError('Acesso ADMIN necessário ou catálogo indisponível.'); } }, [accessToken, levelId, request, stageId]);
  useEffect(() => { void load(); }, [load]);
  const mutate = async (path: string, method: 'POST' | 'PATCH', body: Json) => { try { setError(''); await request(path, { method, headers: { 'content-type': 'application/json' }, body: JSON.stringify(body) }); setNotice('Alteração salva e auditada.'); await load(); } catch { setError('Não foi possível salvar. Verifique os dados, permissões e unicidade.'); } };
  const submitLevel = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const data = new FormData(event.currentTarget); void mutate('/admin/bncc/levels', 'POST', { code: data.get('code'), name: data.get('name') }); event.currentTarget.reset(); };
  const submitStage = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!levelId) return; const data = new FormData(event.currentTarget); const value = (name: string) => data.get(name) === '' ? null : Number(data.get(name)); void mutate(`/admin/bncc/levels/${levelId}/stages`, 'POST', { code: data.get('code'), name: data.get('name'), yearStart: value('yearStart'), yearEnd: value('yearEnd') }); event.currentTarget.reset(); };
  const submitSkill = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!stageId) return; const data = new FormData(event.currentTarget); const examples = String(data.get('examples')).split('\n').map(value => value.trim()).filter(Boolean); void mutate(`/admin/bncc/stages/${stageId}/skills`, 'POST', { code: data.get('code'), axis: data.get('axis') || null, description: data.get('description'), explanation: data.get('explanation'), examples }); event.currentTarget.reset(); };
  const editName = (path: string, current: string) => { const name = window.prompt('Novo nome:', current); if (name?.trim()) void mutate(path, 'PATCH', { name: name.trim() }); };
  const editStage = (stage: Stage) => { const name = window.prompt('Nome da etapa:', stage.nome); if (name === null) return; const yearStart = window.prompt('Ano inicial (vazio para nenhum):', stage.anoInicial?.toString() ?? ''); const yearEnd = window.prompt('Ano final (vazio para nenhum):', stage.anoFinal?.toString() ?? ''); if (yearStart === null || yearEnd === null) return; void mutate(`/admin/bncc/stages/${stage.id}`, 'PATCH', { name: name.trim(), yearStart: yearStart === '' ? null : Number(yearStart), yearEnd: yearEnd === '' ? null : Number(yearEnd) }); };
  const editSkill = (skill: Skill) => { const description = window.prompt('Descrição:', skill.descricao); if (description === null) return; const explanation = window.prompt('Explicação:', skill.explicacao); const axis = window.prompt('Eixo (vazio para pendente):', skill.eixo ?? ''); const examples = window.prompt('Exemplos, um por linha:', skill.exemplos.map(example => example.texto).join('\n')); if (explanation === null || axis === null || examples === null) return; void mutate(`/admin/bncc/skills/${skill.id}`, 'PATCH', { description: description.trim(), explanation: explanation.trim(), axis: axis.trim() || null, examples: examples.split('\n').map(value => value.trim()).filter(Boolean) }); };
  if (!ready) return <p>Verificando sessão…</p>;
  if (!accessToken) return <p>Faça login como ADMIN para administrar o catálogo.</p>;
  return <section><h1>Administração do catálogo BNCC</h1><p>Os controles apenas solicitam mudanças; o backend valida o papel ADMIN, a integridade e registra auditoria.</p>{error && <p role="alert">{error}</p>}{notice && <p role="status">{notice}</p>}<button onClick={() => void load()}>Atualizar catálogo</button>
    <h2>Níveis</h2><form onSubmit={submitLevel}><select name="code" required defaultValue=""><option value="" disabled>Nível</option><option value="EDUCACAO_INFANTIL">Educação Infantil</option><option value="ENSINO_FUNDAMENTAL">Ensino Fundamental</option><option value="ENSINO_MEDIO">Ensino Médio</option></select><input name="name" required maxLength={100} placeholder="Nome"/><button>Criar nível</button></form><ul>{levels.map(level => <li key={level.id}><button onClick={() => { setLevelId(level.id); setStageId(''); }}>{level.nome}</button> — {level.ativo ? 'ativo' : 'inativo'} <button onClick={() => editName(`/admin/bncc/levels/${level.id}`, level.nome)}>Renomear</button> <button onClick={() => void mutate(`/admin/bncc/levels/${level.id}`, 'PATCH', { active: !level.ativo })}>{level.ativo ? 'Desativar' : 'Ativar'}</button></li>)}</ul>
    <h2>Etapas</h2><label>Nível <select value={levelId} onChange={event => { setLevelId(event.target.value); setStageId(''); }}><option value="">Selecione</option>{levels.map(level => <option key={level.id} value={level.id}>{level.nome}</option>)}</select></label><form onSubmit={submitStage}><input name="code" required maxLength={40} placeholder="Código"/><input name="name" required maxLength={100} placeholder="Nome"/><input name="yearStart" type="number" min="1" placeholder="Ano inicial"/><input name="yearEnd" type="number" min="1" placeholder="Ano final"/><button disabled={!levelId}>Criar etapa</button></form><ul>{stages.map(stage => <li key={stage.id}><button onClick={() => setStageId(stage.id)}>{stage.nome}</button> — {stage.ativo ? 'ativa' : 'inativa'} <button onClick={() => editStage(stage)}>Editar</button> <button onClick={() => void mutate(`/admin/bncc/stages/${stage.id}`, 'PATCH', { active: !stage.ativo })}>{stage.ativo ? 'Desativar' : 'Ativar'}</button></li>)}</ul>
    <h2>Habilidades</h2><label>Etapa <select value={stageId} onChange={event => setStageId(event.target.value)}><option value="">Selecione</option>{stages.map(stage => <option key={stage.id} value={stage.id}>{stage.nome}</option>)}</select></label><form onSubmit={submitSkill}><input name="code" required maxLength={40} placeholder="Código BNCC"/><select name="axis">{axisOptions.map(option => <option key={option} value={option}>{option || 'Eixo pendente'}</option>)}</select><textarea name="description" required placeholder="Descrição"/><textarea name="explanation" required placeholder="Explicação"/><textarea name="examples" required placeholder="Um exemplo por linha"/><button disabled={!stageId}>Criar habilidade</button></form><ul>{skills.map(skill => <li key={skill.id}>{skill.codigo} — {skill.ativa ? 'ativa' : 'inativa'} <button onClick={() => editSkill(skill)}>Editar</button> <button onClick={() => void mutate(`/admin/bncc/skills/${skill.id}`, 'PATCH', { active: !skill.ativa })}>{skill.ativa ? 'Desativar' : 'Ativar'}</button></li>)}</ul>
  </section>;
}
