import { BadRequestException, ConflictException, Inject, Injectable, NotFoundException } from '@nestjs/common';
import { AuditResult, Prisma } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { PrismaService } from '../common/prisma.service';
import { CANONICAL_LEVELS } from './bncc.constants';
import { assertQueryYear, assertStageYears } from './bncc.validation';
import { CatalogQueryDto } from './dto/catalog-query.dto';
import { AdminCatalogQueryDto } from './dto/admin-catalog-query.dto';
import { CreateLevelDto, CreateSkillDto, CreateStageDto, UpdateLevelDto, UpdateSkillDto, UpdateStageDto } from './dto/bncc-admin.dto';

const skillInclude = { etapa: { include: { nivel: true } }, exemplos: { orderBy: { ordem: 'asc' as const } } };
@Injectable()
export class BnccService {
  constructor(@Inject(PrismaService) private readonly prisma: PrismaService, @Inject(AuditService) private readonly audit: AuditService) {}
  levels(admin = false) { return this.prisma.nivelEnsino.findMany({ where: admin ? {} : { ativo: true }, orderBy: { codigo: 'asc' } }); }
  async stages(levelId: string, admin = false) { const level = await this.prisma.nivelEnsino.findUnique({ where: { id: levelId } }); if (!level || (!admin && !level.ativo)) throw new NotFoundException('Nível não encontrado.'); return this.prisma.etapaEnsino.findMany({ where: { nivelEnsinoId: levelId, ...(admin ? {} : { ativo: true }) }, orderBy: { codigo: 'asc' } }); }
  async skills(query: CatalogQueryDto) {
    let level: { id: string; codigo: string } | null = null;
    if (query.levelId) { level = await this.prisma.nivelEnsino.findUnique({ where: { id: query.levelId }, select: { id: true, codigo: true } }); if (!level) throw new BadRequestException('Nível inválido.'); assertQueryYear(level.codigo, query.year); }
    else if (query.year !== undefined) throw new BadRequestException('Ano exige nível.');
    if (query.stageId) { const stage = await this.prisma.etapaEnsino.findUnique({ where: { id: query.stageId }, select: { nivelEnsinoId: true, anoInicial: true, anoFinal: true } }); if (!stage || (level && stage.nivelEnsinoId !== level.id)) throw new BadRequestException('Etapa não pertence ao nível selecionado.'); if (query.year !== undefined && (!stage.anoInicial || !stage.anoFinal || query.year < stage.anoInicial || query.year > stage.anoFinal)) throw new BadRequestException('A etapa não contempla o ano informado.'); }
    const conditions: Prisma.HabilidadeBNCCWhereInput[] = [{ ativa: true, etapa: { ativo: true, nivel: { ativo: true } } }];
    if (query.axis) conditions.push({ eixo: query.axis });
    if (query.levelId) conditions.push({ etapa: { is: { nivelEnsinoId: query.levelId } } });
    if (query.stageId) conditions.push({ etapaEnsinoId: query.stageId });
    if (query.year) conditions.push({ etapa: { is: { anoInicial: { lte: query.year }, anoFinal: { gte: query.year } } } });
    if (query.q) conditions.push({ OR: [{ codigo: { contains: query.q, mode: 'insensitive' } }, { descricao: { contains: query.q, mode: 'insensitive' } }, { explicacao: { contains: query.q, mode: 'insensitive' } }, { exemplos: { some: { texto: { contains: query.q, mode: 'insensitive' } } } }] });
    const where: Prisma.HabilidadeBNCCWhereInput = { AND: conditions };
    const [total, data] = await this.prisma.$transaction([this.prisma.habilidadeBNCC.count({ where }), this.prisma.habilidadeBNCC.findMany({ where, include: skillInclude, orderBy: { codigo: 'asc' }, skip: (query.page - 1) * query.pageSize, take: query.pageSize })]);
    return { data, meta: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } };
  }
  async createLevel(dto: CreateLevelDto, actorId: string) { if (!CANONICAL_LEVELS.includes(dto.code as never)) throw new BadRequestException('Nível não permitido.'); try { return await this.prisma.$transaction(async tx => { const item = await tx.nivelEnsino.create({ data: { codigo: dto.code, nome: dto.name.trim() } }); await this.audit.logWith(tx, 'BNCC_LEVEL_CREATED', AuditResult.SUCCESS, actorId, undefined, { catalogId: item.id }); return item; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException('Nível já existe.'); throw e; } }
  async updateLevel(id: string, dto: UpdateLevelDto, actorId: string) { try { return await this.prisma.$transaction(async tx => { const item = await tx.nivelEnsino.update({ where: { id }, data: { ...(dto.name ? { nome: dto.name.trim() } : {}), ...(dto.active !== undefined ? { ativo: dto.active } : {}) } }); await this.audit.logWith(tx, 'BNCC_LEVEL_UPDATED', AuditResult.SUCCESS, actorId, undefined, { catalogId: id }); return item; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException('Nível já existe.'); if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2025') throw new NotFoundException('Nível não encontrado.'); throw e; } }
  async createStage(levelId: string, dto: CreateStageDto, actorId: string) { const level = await this.prisma.nivelEnsino.findUnique({ where: { id: levelId } }); if (!level) throw new NotFoundException('Nível não encontrado.'); assertStageYears(level.codigo, dto.yearStart ?? null, dto.yearEnd ?? null); try { return await this.prisma.$transaction(async tx => { const item = await tx.etapaEnsino.create({ data: { nivelEnsinoId: levelId, codigo: dto.code.trim().toUpperCase(), nome: dto.name.trim(), anoInicial: dto.yearStart ?? null, anoFinal: dto.yearEnd ?? null } }); await this.audit.logWith(tx, 'BNCC_STAGE_CREATED', AuditResult.SUCCESS, actorId, undefined, { catalogId: item.id }); return item; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException('Etapa duplicada.'); throw e; } }
  async updateStage(id: string, dto: UpdateStageDto, actorId: string) { const stage = await this.prisma.etapaEnsino.findUnique({ where: { id }, include: { nivel: true } }); if (!stage) throw new NotFoundException('Etapa não encontrada.'); const start = dto.yearStart === undefined ? stage.anoInicial : dto.yearStart; const end = dto.yearEnd === undefined ? stage.anoFinal : dto.yearEnd; assertStageYears(stage.nivel.codigo, start ?? null, end ?? null); try { return await this.prisma.$transaction(async tx => { const item = await tx.etapaEnsino.update({ where: { id }, data: { ...(dto.name ? { nome: dto.name.trim() } : {}), ...(dto.yearStart !== undefined ? { anoInicial: dto.yearStart } : {}), ...(dto.yearEnd !== undefined ? { anoFinal: dto.yearEnd } : {}), ...(dto.active !== undefined ? { ativo: dto.active } : {}) } }); await this.audit.logWith(tx, 'BNCC_STAGE_UPDATED', AuditResult.SUCCESS, actorId, undefined, { catalogId: id }); return item; }); } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException('Etapa duplicada.'); throw e; } }
  async createSkill(stageId: string, dto: CreateSkillDto, actorId: string) { const stage = await this.prisma.etapaEnsino.findUnique({ where: { id: stageId } }); if (!stage) throw new NotFoundException('Etapa não encontrada.'); try { const item = await this.prisma.$transaction(async tx => { const result = await tx.habilidadeBNCC.create({ data: { etapaEnsinoId: stageId, codigo: dto.code.trim().toUpperCase(), eixo: dto.axis ?? null, descricao: dto.description.trim(), explicacao: dto.explanation.trim(), exemplos: { create: dto.examples.map((texto, i) => ({ texto: texto.trim(), ordem: i + 1 })) } }, include: skillInclude }); await this.audit.logWith(tx, 'BNCC_SKILL_CREATED', AuditResult.SUCCESS, actorId, undefined, { catalogId: result.id }); return result; }); return item; } catch (e) { if (e instanceof Prisma.PrismaClientKnownRequestError && e.code === 'P2002') throw new ConflictException('Código BNCC já existe.'); throw e; } }
  async updateSkill(id: string, dto: UpdateSkillDto, actorId: string) { const exists = await this.prisma.habilidadeBNCC.findUnique({ where: { id } }); if (!exists) throw new NotFoundException('Habilidade não encontrada.'); const item = await this.prisma.$transaction(async tx => { if (dto.examples) await tx.exemploHabilidadeBNCC.deleteMany({ where: { habilidadeBNCCId: id } }); const result = await tx.habilidadeBNCC.update({ where: { id }, data: { ...(dto.axis !== undefined ? { eixo: dto.axis } : {}), ...(dto.description ? { descricao: dto.description.trim() } : {}), ...(dto.explanation ? { explicacao: dto.explanation.trim() } : {}), ...(dto.active !== undefined ? { ativa: dto.active } : {}), ...(dto.examples ? { exemplos: { create: dto.examples.map((texto, i) => ({ texto: texto.trim(), ordem: i + 1 })) } } : {}) }, include: skillInclude }); await this.audit.logWith(tx, 'BNCC_SKILL_UPDATED', AuditResult.SUCCESS, actorId, undefined, { catalogId: id }); return result; }); return item; }
  async adminSkills(query: AdminCatalogQueryDto) { const conditions: Prisma.HabilidadeBNCCWhereInput[] = []; if (query.levelId) conditions.push({ etapa: { is: { nivelEnsinoId: query.levelId } } }); if (query.stageId) conditions.push({ etapaEnsinoId: query.stageId }); if (query.active !== undefined) conditions.push({ ativa: query.active }); if (query.q) conditions.push({ OR: [{ codigo: { contains: query.q, mode: 'insensitive' } }, { descricao: { contains: query.q, mode: 'insensitive' } }, { explicacao: { contains: query.q, mode: 'insensitive' } }, { exemplos: { some: { texto: { contains: query.q, mode: 'insensitive' } } } }] }); const where: Prisma.HabilidadeBNCCWhereInput = conditions.length ? { AND: conditions } : {}; const [total, data] = await this.prisma.$transaction([this.prisma.habilidadeBNCC.count({ where }), this.prisma.habilidadeBNCC.findMany({ where, include: skillInclude, orderBy: { codigo: 'asc' }, skip: (query.page - 1) * query.pageSize, take: query.pageSize })]); return { data, meta: { page: query.page, pageSize: query.pageSize, total, totalPages: Math.ceil(total / query.pageSize) } }; }
}
